/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.1, generation date: 2023/06/17 01:44:50
DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00, 
SRC_NAME: TPCH_SF1 - Release: TPCH_SF1(1) - Comment: Release 1 of TPCH - Release date: 2023/06/17 01:37:07
 */

/* DROP TABLES */
-- START
DROP TABLE IF EXISTS "TPCH_SF1_MTD"."FMC_LOADING_WINDOW_TABLE" 
CASCADE
;
DROP TABLE IF EXISTS "TPCH_SF1_MTD"."LOAD_CYCLE_INFO" 
CASCADE
;
DROP TABLE IF EXISTS "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS" 
CASCADE
;

-- END


/* CREATE TABLES */
-- START

CREATE   TABLE "TPCH_SF1_MTD"."FMC_LOADING_WINDOW_TABLE"
(
	"FMC_BEGIN_LW_TIMESTAMP" TIMESTAMP_NTZ,
	"FMC_END_LW_TIMESTAMP" TIMESTAMP_NTZ
)
;

COMMENT ON TABLE "TPCH_SF1_MTD"."FMC_LOADING_WINDOW_TABLE" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00, 
SRC_NAME: TPCH_SF1 - Release: TPCH_SF1(1) - Comment: Release 1 of TPCH - Release date: 2023/06/17 01:37:07';


CREATE   TABLE "TPCH_SF1_MTD"."LOAD_CYCLE_INFO"
(
	"LOAD_CYCLE_ID" INTEGER,
	"LOAD_DATE" TIMESTAMP_NTZ
)
;

COMMENT ON TABLE "TPCH_SF1_MTD"."LOAD_CYCLE_INFO" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00, 
SRC_NAME: TPCH_SF1 - Release: TPCH_SF1(1) - Comment: Release 1 of TPCH - Release date: 2023/06/17 01:37:07';


CREATE   TABLE "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS"
(
	"LOAD_CYCLE_ID" VARCHAR(3),
	"RECORD_TYPE" VARCHAR(3),
	"KEY_ATTRIBUTE_BOOLEAN" VARCHAR(5),
	"KEY_ATTRIBUTE_DATE" VARCHAR(10),
	"KEY_ATTRIBUTE_FLOAT" VARCHAR(3),
	"KEY_ATTRIBUTE_INTEGER" VARCHAR(11),
	"KEY_ATTRIBUTE_TIME" VARCHAR(8),
	"KEY_ATTRIBUTE_TIMESTAMP_NTZ" VARCHAR(19),
	"KEY_ATTRIBUTE_VARCHAR" VARCHAR(3),
	"ATTRIBUTE_BOOLEAN" VARCHAR(5),
	"ATTRIBUTE_DATE" VARCHAR(10),
	"ATTRIBUTE_FLOAT" VARCHAR(3),
	"ATTRIBUTE_INTEGER" VARCHAR(11),
	"ATTRIBUTE_TIME" VARCHAR(8),
	"ATTRIBUTE_TIMESTAMP_NTZ" VARCHAR(19),
	"ATTRIBUTE_VARCHAR" VARCHAR(3)
)
;

COMMENT ON TABLE "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00, 
SRC_NAME: TPCH_SF1 - Release: TPCH_SF1(1) - Comment: Release 1 of TPCH - Release date: 2023/06/17 01:37:07';


INSERT INTO "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS"
("LOAD_CYCLE_ID", "RECORD_TYPE", "KEY_ATTRIBUTE_BOOLEAN", "KEY_ATTRIBUTE_DATE", "KEY_ATTRIBUTE_FLOAT", "KEY_ATTRIBUTE_INTEGER", "KEY_ATTRIBUTE_TIME", "KEY_ATTRIBUTE_TIMESTAMP_NTZ", "KEY_ATTRIBUTE_VARCHAR", "ATTRIBUTE_BOOLEAN", "ATTRIBUTE_DATE", "ATTRIBUTE_FLOAT", "ATTRIBUTE_INTEGER", "ATTRIBUTE_TIME", "ATTRIBUTE_TIMESTAMP_NTZ", "ATTRIBUTE_VARCHAR") VALUES ('-2','U','false','01/01/2899','-2','-2147483647','24:00:00','01/01/2899 00:00:00','~?~','false','01/01/2899','-2','-2147483647','24:00:00','01/01/2899 00:00:00','~?~');

INSERT INTO "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS"
("LOAD_CYCLE_ID", "RECORD_TYPE", "KEY_ATTRIBUTE_BOOLEAN", "KEY_ATTRIBUTE_DATE", "KEY_ATTRIBUTE_FLOAT", "KEY_ATTRIBUTE_INTEGER", "KEY_ATTRIBUTE_TIME", "KEY_ATTRIBUTE_TIMESTAMP_NTZ", "KEY_ATTRIBUTE_VARCHAR", "ATTRIBUTE_BOOLEAN", "ATTRIBUTE_DATE", "ATTRIBUTE_FLOAT", "ATTRIBUTE_INTEGER", "ATTRIBUTE_TIME", "ATTRIBUTE_TIMESTAMP_NTZ", "ATTRIBUTE_VARCHAR") VALUES ('-1','N','false','01/01/2999','-1','-2147483648','00:00:00','01/01/2999 00:00:00','0','false','01/01/2999','-1','-2147483648','00:00:00','01/01/2999 00:00:00','0');

-- END


