/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.1, generation date: 2023/06/17 01:44:50
DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00
 */

/* DROP TABLES */

-- START
DROP TABLE IF EXISTS "TPCH_SF1_STG"."LDS_TPCH_PARTSUPP_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "TPCH_SF1_STG"."SAT_TPCH_PART_TMP" 
CASCADE
;
DROP TABLE IF EXISTS "TPCH_SF1_STG"."SAT_TPCH_SUPPLIER_TMP" 
CASCADE
;

-- END


/* CREATE TABLES */

-- START

CREATE   TABLE "TPCH_SF1_STG"."SAT_TPCH_PART_TMP"
(
    "PART_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_TIMESTAMP" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"P_PARTKEY" INTEGER
   ,"P_NAME" VARCHAR
   ,"P_MFGR" VARCHAR
   ,"P_BRAND" VARCHAR
   ,"P_TYPE" VARCHAR
   ,"P_SIZE" INTEGER
   ,"P_CONTAINER" VARCHAR
   ,"P_RETAILPRICE" INTEGER
   ,"P_COMMENT" VARCHAR
   ,"LOAD_TIMESTAMP" TIMESTAMP_NTZ(9)
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
)
;

COMMENT ON TABLE "TPCH_SF1_STG"."SAT_TPCH_PART_TMP" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00';


CREATE   TABLE "TPCH_SF1_STG"."SAT_TPCH_SUPPLIER_TMP"
(
    "SUPPLIER_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_TIMESTAMP" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"S_SUPPKEY" INTEGER
   ,"S_NAME" VARCHAR
   ,"S_ADDRESS" VARCHAR
   ,"S_NATIONKEY" INTEGER
   ,"S_PHONE" VARCHAR
   ,"S_ACCTBAL" INTEGER
   ,"S_COMMENT" VARCHAR
   ,"LOAD_TIMESTAMP" TIMESTAMP_NTZ(9)
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
)
;

COMMENT ON TABLE "TPCH_SF1_STG"."SAT_TPCH_SUPPLIER_TMP" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00';


CREATE   TABLE "TPCH_SF1_STG"."LDS_TPCH_PARTSUPP_TMP"
(
    "LND_PARTSUPP_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_TIMESTAMP" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"PS_PARTKEY" INTEGER
   ,"PS_SUPPKEY" INTEGER
   ,"PS_AVAILQTY" INTEGER
   ,"PS_SUPPLYCOST" INTEGER
   ,"PS_COMMENT" VARCHAR
   ,"LOAD_TIMESTAMP" TIMESTAMP_NTZ(9)
   ,"SOURCE" VARCHAR
   ,"EQUAL" NUMBER
   ,"RECORD_TYPE" VARCHAR
   ,"SUPPLIER_HKEY" VARCHAR(32)
   ,"PART_HKEY" VARCHAR(32)
)
;

COMMENT ON TABLE "TPCH_SF1_STG"."LDS_TPCH_PARTSUPP_TMP" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00';


-- END


