/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.1, generation date: 2023/06/17 01:44:50
DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00
 */

/* DROP TABLES */

-- START
DROP TABLE IF EXISTS "TPCH_DV_FL"."LDS_TPCH_PARTSUPP" 
CASCADE
;
DROP TABLE IF EXISTS "TPCH_DV_FL"."LND_PARTSUPP" 
CASCADE
;
DROP TABLE IF EXISTS "TPCH_DV_FL"."SAT_TPCH_PART" 
CASCADE
;
DROP TABLE IF EXISTS "TPCH_DV_FL"."SAT_TPCH_SUPPLIER" 
CASCADE
;
DROP TABLE IF EXISTS "TPCH_DV_FL"."HUB_PART" 
CASCADE
;
DROP TABLE IF EXISTS "TPCH_DV_FL"."HUB_SUPPLIER" 
CASCADE
;

-- END


/* CREATE TABLES */

-- START

CREATE   TABLE "TPCH_DV_FL"."HUB_PART"
(
    "PART_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"SRC_BK" VARCHAR DEFAULT '0' NOT NULL
   ,"P_PARTKEY_BK" VARCHAR(1500)
   ,CONSTRAINT "HUB_PART_PK" PRIMARY KEY ("PART_HKEY")   
   ,CONSTRAINT "HUB_PART_UK" UNIQUE ("P_PARTKEY_BK", "SRC_BK")   
)
;

COMMENT ON TABLE "TPCH_DV_FL"."HUB_PART" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00';


CREATE   TABLE "TPCH_DV_FL"."HUB_SUPPLIER"
(
    "SUPPLIER_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"SRC_BK" VARCHAR DEFAULT '0' NOT NULL
   ,"S_SUPPKEY_BK" VARCHAR(1500)
   ,CONSTRAINT "HUB_SUPPLIER_PK" PRIMARY KEY ("SUPPLIER_HKEY")   
   ,CONSTRAINT "HUB_SUPPLIER_UK" UNIQUE ("S_SUPPKEY_BK", "SRC_BK")   
)
;

COMMENT ON TABLE "TPCH_DV_FL"."HUB_SUPPLIER" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00';


CREATE   TABLE "TPCH_DV_FL"."SAT_TPCH_PART"
(
    "PART_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_TIMESTAMP" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"P_PARTKEY" INTEGER
   ,"P_NAME" VARCHAR
   ,"P_MFGR" VARCHAR
   ,"P_BRAND" VARCHAR
   ,"P_TYPE" VARCHAR
   ,"P_SIZE" INTEGER
   ,"P_CONTAINER" VARCHAR
   ,"P_RETAILPRICE" INTEGER
   ,"P_COMMENT" VARCHAR
   ,"LOAD_TIMESTAMP" TIMESTAMP_NTZ(9)
   ,CONSTRAINT "SAT_TPCH_PART_UK" UNIQUE ("PART_HKEY", "LOAD_DATE")   
)
;

ALTER TABLE "TPCH_DV_FL"."SAT_TPCH_PART" ADD CONSTRAINT "SAT_TPCH_PART_FK" FOREIGN KEY ("PART_HKEY") REFERENCES "TPCH_DV_FL"."HUB_PART"("PART_HKEY");
COMMENT ON TABLE "TPCH_DV_FL"."SAT_TPCH_PART" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00';


CREATE   TABLE "TPCH_DV_FL"."SAT_TPCH_SUPPLIER"
(
    "SUPPLIER_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_TIMESTAMP" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"S_SUPPKEY" INTEGER
   ,"S_NAME" VARCHAR
   ,"S_ADDRESS" VARCHAR
   ,"S_NATIONKEY" INTEGER
   ,"S_PHONE" VARCHAR
   ,"S_ACCTBAL" INTEGER
   ,"S_COMMENT" VARCHAR
   ,"LOAD_TIMESTAMP" TIMESTAMP_NTZ(9)
   ,CONSTRAINT "SAT_TPCH_SUPPLIER_UK" UNIQUE ("SUPPLIER_HKEY", "LOAD_DATE")   
)
;

ALTER TABLE "TPCH_DV_FL"."SAT_TPCH_SUPPLIER" ADD CONSTRAINT "SAT_TPCH_SUPPLIER_FK" FOREIGN KEY ("SUPPLIER_HKEY") REFERENCES "TPCH_DV_FL"."HUB_SUPPLIER"("SUPPLIER_HKEY");
COMMENT ON TABLE "TPCH_DV_FL"."SAT_TPCH_SUPPLIER" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00';


CREATE   TABLE "TPCH_DV_FL"."LND_PARTSUPP"
(
    "LND_PARTSUPP_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"PART_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"SUPPLIER_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,CONSTRAINT "LND_PARTSUPP_PK" PRIMARY KEY ("LND_PARTSUPP_HKEY")   
   ,CONSTRAINT "LND_PARTSUPP_UK" UNIQUE ("PART_HKEY", "SUPPLIER_HKEY")   
)
;

ALTER TABLE "TPCH_DV_FL"."LND_PARTSUPP" ADD CONSTRAINT "LND_PARTSUPP_PART_FK" FOREIGN KEY ("PART_HKEY") REFERENCES "TPCH_DV_FL"."HUB_PART"("PART_HKEY");
ALTER TABLE "TPCH_DV_FL"."LND_PARTSUPP" ADD CONSTRAINT "LND_PARTSUPP_SUPPLIER_FK" FOREIGN KEY ("SUPPLIER_HKEY") REFERENCES "TPCH_DV_FL"."HUB_SUPPLIER"("SUPPLIER_HKEY");
COMMENT ON TABLE "TPCH_DV_FL"."LND_PARTSUPP" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00';


CREATE   TABLE "TPCH_DV_FL"."LDS_TPCH_PARTSUPP"
(
    "LND_PARTSUPP_HKEY" VARCHAR(32) DEFAULT '0' NOT NULL
   ,"LOAD_DATE" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"LOAD_CYCLE_ID" INTEGER DEFAULT -2147483648 NOT NULL
   ,"HASH_DIFF" VARCHAR(32)
   ,"DELETE_FLAG" VARCHAR(3) DEFAULT '0' NOT NULL
   ,"CDC_TIMESTAMP" TIMESTAMP_NTZ DEFAULT TO_TIMESTAMP('01/01/2999 00:00:00', 'DD/MM/YYYY HH24:MI:SS') NOT NULL
   ,"PS_PARTKEY" INTEGER
   ,"PS_SUPPKEY" INTEGER
   ,"PS_AVAILQTY" INTEGER
   ,"PS_SUPPLYCOST" INTEGER
   ,"PS_COMMENT" VARCHAR
   ,"LOAD_TIMESTAMP" TIMESTAMP_NTZ(9)
   ,CONSTRAINT "LDS_TPCH_PARTSUPP_UK" UNIQUE ("LND_PARTSUPP_HKEY", "LOAD_DATE")   
)
;

ALTER TABLE "TPCH_DV_FL"."LDS_TPCH_PARTSUPP" ADD CONSTRAINT "LDS_TPCH_PARTSUPP_FK" FOREIGN KEY ("LND_PARTSUPP_HKEY") REFERENCES "TPCH_DV_FL"."LND_PARTSUPP"("LND_PARTSUPP_HKEY");
COMMENT ON TABLE "TPCH_DV_FL"."LDS_TPCH_PARTSUPP" IS 'DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 01:44:00';


-- END


