/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.1, generation date: 2023/06/17 03:45:02
DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 03:44:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/17 01:44:13, 
SRC_NAME: TPCH_SF1 - Release: TPCH_SF1(1) - Comment: Release 1 of TPCH - Release date: 2023/06/17 03:37:07
 */


DROP VIEW IF EXISTS "TPCH_SF1_DFV"."VW_PART";
CREATE  VIEW "TPCH_SF1_DFV"."VW_PART"  AS 
	WITH "DELTA_WINDOW" AS 
	( 
		SELECT 
			  "LWT_SRC"."FMC_BEGIN_LW_TIMESTAMP" AS "FMC_BEGIN_LW_TIMESTAMP"
			, "LWT_SRC"."FMC_END_LW_TIMESTAMP" AS "FMC_END_LW_TIMESTAMP"
		FROM "TPCH_SF1_MTD"."FMC_LOADING_WINDOW_TABLE" "LWT_SRC"
	)
	, "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  "CDC_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, 'S' ::varchar AS "RECORD_TYPE"
			, "CDC_SRC"."P_PARTKEY" AS "P_PARTKEY"
			, "CDC_SRC"."P_NAME" AS "P_NAME"
			, "CDC_SRC"."P_MFGR" AS "P_MFGR"
			, "CDC_SRC"."P_BRAND" AS "P_BRAND"
			, "CDC_SRC"."P_TYPE" AS "P_TYPE"
			, "CDC_SRC"."P_SIZE" AS "P_SIZE"
			, "CDC_SRC"."P_CONTAINER" AS "P_CONTAINER"
			, "CDC_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "CDC_SRC"."P_COMMENT" AS "P_COMMENT"
			, "CDC_SRC"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		FROM "TPCH_SF1_CDC"."CDC_PART" "CDC_SRC"
		INNER JOIN "DELTA_WINDOW" "DELTA_WINDOW" ON  1 = 1
		WHERE  "CDC_SRC"."CDC_TIMESTAMP" > "DELTA_WINDOW"."FMC_BEGIN_LW_TIMESTAMP" AND "CDC_SRC"."CDC_TIMESTAMP" <= "DELTA_WINDOW"."FMC_END_LW_TIMESTAMP"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."P_PARTKEY" AS "P_PARTKEY"
			, "DELTA_VIEW_FILTER"."P_NAME" AS "P_NAME"
			, "DELTA_VIEW_FILTER"."P_MFGR" AS "P_MFGR"
			, "DELTA_VIEW_FILTER"."P_BRAND" AS "P_BRAND"
			, "DELTA_VIEW_FILTER"."P_TYPE" AS "P_TYPE"
			, "DELTA_VIEW_FILTER"."P_SIZE" AS "P_SIZE"
			, "DELTA_VIEW_FILTER"."P_CONTAINER" AS "P_CONTAINER"
			, "DELTA_VIEW_FILTER"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "DELTA_VIEW_FILTER"."P_COMMENT" AS "P_COMMENT"
			, "DELTA_VIEW_FILTER"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."P_PARTKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_INTEGER" AS INTEGER)) AS "P_PARTKEY"
			, "DELTA_VIEW"."P_NAME" AS "P_NAME"
			, "DELTA_VIEW"."P_MFGR" AS "P_MFGR"
			, "DELTA_VIEW"."P_BRAND" AS "P_BRAND"
			, "DELTA_VIEW"."P_TYPE" AS "P_TYPE"
			, "DELTA_VIEW"."P_SIZE" AS "P_SIZE"
			, "DELTA_VIEW"."P_CONTAINER" AS "P_CONTAINER"
			, "DELTA_VIEW"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "DELTA_VIEW"."P_COMMENT" AS "P_COMMENT"
			, "DELTA_VIEW"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS" "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."P_PARTKEY" AS "P_PARTKEY"
		, "PREPJOINBK"."P_NAME" AS "P_NAME"
		, "PREPJOINBK"."P_MFGR" AS "P_MFGR"
		, "PREPJOINBK"."P_BRAND" AS "P_BRAND"
		, "PREPJOINBK"."P_TYPE" AS "P_TYPE"
		, "PREPJOINBK"."P_SIZE" AS "P_SIZE"
		, "PREPJOINBK"."P_CONTAINER" AS "P_CONTAINER"
		, "PREPJOINBK"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "PREPJOINBK"."P_COMMENT" AS "P_COMMENT"
		, "PREPJOINBK"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
	FROM "PREPJOINBK" "PREPJOINBK"
	;

 
 
