/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.1, generation date: 2023/06/17 03:45:02
DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 03:44:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/17 01:44:13, 
SRC_NAME: TPCH_SF1 - Release: TPCH_SF1(1) - Comment: Release 1 of TPCH - Release date: 2023/06/17 03:37:07
 */


DROP VIEW IF EXISTS "TPCH_SF1_DFV"."VW_SUPPLIER";
CREATE  VIEW "TPCH_SF1_DFV"."VW_SUPPLIER"  AS 
	WITH "DELTA_WINDOW" AS 
	( 
		SELECT 
			  "LWT_SRC"."FMC_BEGIN_LW_TIMESTAMP" AS "FMC_BEGIN_LW_TIMESTAMP"
			, "LWT_SRC"."FMC_END_LW_TIMESTAMP" AS "FMC_END_LW_TIMESTAMP"
		FROM "TPCH_SF1_MTD"."FMC_LOADING_WINDOW_TABLE" "LWT_SRC"
	)
	, "DELTA_VIEW_FILTER" AS 
	( 
		SELECT 
			  "CDC_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, 'S' ::varchar AS "RECORD_TYPE"
			, "CDC_SRC"."S_SUPPKEY" AS "S_SUPPKEY"
			, "CDC_SRC"."S_NAME" AS "S_NAME"
			, "CDC_SRC"."S_ADDRESS" AS "S_ADDRESS"
			, "CDC_SRC"."S_NATIONKEY" AS "S_NATIONKEY"
			, "CDC_SRC"."S_PHONE" AS "S_PHONE"
			, "CDC_SRC"."S_ACCTBAL" AS "S_ACCTBAL"
			, "CDC_SRC"."S_COMMENT" AS "S_COMMENT"
			, "CDC_SRC"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		FROM "TPCH_SF1_CDC"."CDC_SUPPLIER" "CDC_SRC"
		INNER JOIN "DELTA_WINDOW" "DELTA_WINDOW" ON  1 = 1
		WHERE  "CDC_SRC"."CDC_TIMESTAMP" > "DELTA_WINDOW"."FMC_BEGIN_LW_TIMESTAMP" AND "CDC_SRC"."CDC_TIMESTAMP" <= "DELTA_WINDOW"."FMC_END_LW_TIMESTAMP"
	)
	, "DELTA_VIEW" AS 
	( 
		SELECT 
			  "DELTA_VIEW_FILTER"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW_FILTER"."RECORD_TYPE" AS "RECORD_TYPE"
			, "DELTA_VIEW_FILTER"."S_SUPPKEY" AS "S_SUPPKEY"
			, "DELTA_VIEW_FILTER"."S_NAME" AS "S_NAME"
			, "DELTA_VIEW_FILTER"."S_ADDRESS" AS "S_ADDRESS"
			, "DELTA_VIEW_FILTER"."S_NATIONKEY" AS "S_NATIONKEY"
			, "DELTA_VIEW_FILTER"."S_PHONE" AS "S_PHONE"
			, "DELTA_VIEW_FILTER"."S_ACCTBAL" AS "S_ACCTBAL"
			, "DELTA_VIEW_FILTER"."S_COMMENT" AS "S_COMMENT"
			, "DELTA_VIEW_FILTER"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		FROM "DELTA_VIEW_FILTER" "DELTA_VIEW_FILTER"
	)
	, "PREPJOINBK" AS 
	( 
		SELECT 
			  "DELTA_VIEW"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "DELTA_VIEW"."RECORD_TYPE" AS "RECORD_TYPE"
			, COALESCE("DELTA_VIEW"."S_SUPPKEY", CAST("MEX_BK_SRC"."KEY_ATTRIBUTE_INTEGER" AS INTEGER)) AS "S_SUPPKEY"
			, "DELTA_VIEW"."S_NAME" AS "S_NAME"
			, "DELTA_VIEW"."S_ADDRESS" AS "S_ADDRESS"
			, "DELTA_VIEW"."S_NATIONKEY" AS "S_NATIONKEY"
			, "DELTA_VIEW"."S_PHONE" AS "S_PHONE"
			, "DELTA_VIEW"."S_ACCTBAL" AS "S_ACCTBAL"
			, "DELTA_VIEW"."S_COMMENT" AS "S_COMMENT"
			, "DELTA_VIEW"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		FROM "DELTA_VIEW" "DELTA_VIEW"
		INNER JOIN "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS" "MEX_BK_SRC" ON  1 = 1
		WHERE  "MEX_BK_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "PREPJOINBK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "PREPJOINBK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "PREPJOINBK"."S_SUPPKEY" AS "S_SUPPKEY"
		, "PREPJOINBK"."S_NAME" AS "S_NAME"
		, "PREPJOINBK"."S_ADDRESS" AS "S_ADDRESS"
		, "PREPJOINBK"."S_NATIONKEY" AS "S_NATIONKEY"
		, "PREPJOINBK"."S_PHONE" AS "S_PHONE"
		, "PREPJOINBK"."S_ACCTBAL" AS "S_ACCTBAL"
		, "PREPJOINBK"."S_COMMENT" AS "S_COMMENT"
		, "PREPJOINBK"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
	FROM "PREPJOINBK" "PREPJOINBK"
	;

 
 
