CREATE OR REPLACE PROCEDURE "SF_SAMPLE_PROC"."EXT_TPCH_PART_INIT"()
 RETURNS varchar 
LANGUAGE JAVASCRIPT 

AS $$ 
/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.1, generation date: 2023/06/17 03:45:02
DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 03:44:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/17 01:44:13, 
SRC_NAME: TPCH_SF1 - Release: TPCH_SF1(1) - Comment: Release 1 of TPCH - Release date: 2023/06/17 03:37:07
 */



var truncate_EXT_TGT = snowflake.createStatement( {sqlText: `
	TRUNCATE TABLE "TPCH_SF1_EXT"."PART";
`} ).execute();


var EXT_TGT = snowflake.createStatement( {sqlText: `
	INSERT INTO "TPCH_SF1_EXT"."PART"(
		 "LOAD_CYCLE_ID"
		,"LOAD_DATE"
		,"CDC_TIMESTAMP"
		,"JRN_FLAG"
		,"RECORD_TYPE"
		,"P_PARTKEY"
		,"P_PARTKEY_BK"
		,"P_NAME"
		,"P_MFGR"
		,"P_BRAND"
		,"P_TYPE"
		,"P_SIZE"
		,"P_CONTAINER"
		,"P_RETAILPRICE"
		,"P_COMMENT"
		,"LOAD_TIMESTAMP"
	)
	WITH "LOAD_INIT_DATA" AS 
	( 
		SELECT 
			  'I' ::varchar AS "JRN_FLAG"
			, "INI_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, 'S'::varchar AS "RECORD_TYPE"
			, COALESCE("INI_SRC"."P_PARTKEY", CAST("MEX_INR_SRC"."KEY_ATTRIBUTE_INTEGER" AS INTEGER)) AS "P_PARTKEY"
			, "INI_SRC"."P_NAME" AS "P_NAME"
			, "INI_SRC"."P_MFGR" AS "P_MFGR"
			, "INI_SRC"."P_BRAND" AS "P_BRAND"
			, "INI_SRC"."P_TYPE" AS "P_TYPE"
			, "INI_SRC"."P_SIZE" AS "P_SIZE"
			, "INI_SRC"."P_CONTAINER" AS "P_CONTAINER"
			, "INI_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "INI_SRC"."P_COMMENT" AS "P_COMMENT"
			, "INI_SRC"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		FROM "TPCH_SF1"."PART" "INI_SRC"
		INNER JOIN "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS" "MEX_INR_SRC" ON  "MEX_INR_SRC"."RECORD_TYPE" = 'N'
	)
	, "PREP_EXCEP" AS 
	( 
		SELECT 
			  "LOAD_INIT_DATA"."JRN_FLAG" AS "JRN_FLAG"
			, "LOAD_INIT_DATA"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "LOAD_INIT_DATA"."RECORD_TYPE" AS "RECORD_TYPE"
			, NULL AS "LOAD_CYCLE_ID"
			, "LOAD_INIT_DATA"."P_PARTKEY" AS "P_PARTKEY"
			, "LOAD_INIT_DATA"."P_NAME" AS "P_NAME"
			, "LOAD_INIT_DATA"."P_MFGR" AS "P_MFGR"
			, "LOAD_INIT_DATA"."P_BRAND" AS "P_BRAND"
			, "LOAD_INIT_DATA"."P_TYPE" AS "P_TYPE"
			, "LOAD_INIT_DATA"."P_SIZE" AS "P_SIZE"
			, "LOAD_INIT_DATA"."P_CONTAINER" AS "P_CONTAINER"
			, "LOAD_INIT_DATA"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "LOAD_INIT_DATA"."P_COMMENT" AS "P_COMMENT"
			, "LOAD_INIT_DATA"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		FROM "LOAD_INIT_DATA" "LOAD_INIT_DATA"
		UNION ALL 
		SELECT 
			  'I' ::varchar AS "JRN_FLAG"
			, TO_TIMESTAMP_NTZ("MEX_EXT_SRC"."KEY_ATTRIBUTE_TIMESTAMP_NTZ", 'DD/MM/YYYY HH24:MI:SS') AS "CDC_TIMESTAMP"
			, "MEX_EXT_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, "MEX_EXT_SRC"."LOAD_CYCLE_ID" ::integer AS "LOAD_CYCLE_ID"
			, CAST("MEX_EXT_SRC"."KEY_ATTRIBUTE_INTEGER" AS INTEGER) AS "P_PARTKEY"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_NAME"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_MFGR"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_BRAND"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_TYPE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_INTEGER" AS INTEGER) AS "P_SIZE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_CONTAINER"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_INTEGER" AS INTEGER) AS "P_RETAILPRICE"
			, CAST("MEX_EXT_SRC"."ATTRIBUTE_VARCHAR" AS VARCHAR) AS "P_COMMENT"
			, TO_TIMESTAMP_NTZ("MEX_EXT_SRC"."ATTRIBUTE_TIMESTAMP_NTZ", 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_TIMESTAMP"
		FROM "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS" "MEX_EXT_SRC"
	)
	, "CALCULATE_BK" AS 
	( 
		SELECT 
			  COALESCE("PREP_EXCEP"."LOAD_CYCLE_ID","LCI_SRC"."LOAD_CYCLE_ID") AS "LOAD_CYCLE_ID"
			, "LCI_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, CASE WHEN "PREP_EXCEP"."RECORD_TYPE" = 'S' THEN "PREP_EXCEP"."CDC_TIMESTAMP" ELSE "LCI_SRC"."LOAD_DATE" END AS "CDC_TIMESTAMP"
			, "PREP_EXCEP"."JRN_FLAG" AS "JRN_FLAG"
			, "PREP_EXCEP"."RECORD_TYPE" AS "RECORD_TYPE"
			, "PREP_EXCEP"."P_PARTKEY" AS "P_PARTKEY"
			, COALESCE(UPPER( TO_CHAR("PREP_EXCEP"."P_PARTKEY")),"MEX_SRC"."KEY_ATTRIBUTE_INTEGER") AS "P_PARTKEY_BK"
			, "PREP_EXCEP"."P_NAME" AS "P_NAME"
			, "PREP_EXCEP"."P_MFGR" AS "P_MFGR"
			, "PREP_EXCEP"."P_BRAND" AS "P_BRAND"
			, "PREP_EXCEP"."P_TYPE" AS "P_TYPE"
			, "PREP_EXCEP"."P_SIZE" AS "P_SIZE"
			, "PREP_EXCEP"."P_CONTAINER" AS "P_CONTAINER"
			, "PREP_EXCEP"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "PREP_EXCEP"."P_COMMENT" AS "P_COMMENT"
			, "PREP_EXCEP"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		FROM "PREP_EXCEP" "PREP_EXCEP"
		INNER JOIN "TPCH_SF1_MTD"."LOAD_CYCLE_INFO" "LCI_SRC" ON  1 = 1
		INNER JOIN "TPCH_SF1_MTD"."MTD_EXCEPTION_RECORDS" "MEX_SRC" ON  1 = 1
		WHERE  "MEX_SRC"."RECORD_TYPE" = 'N'
	)
	SELECT 
		  "CALCULATE_BK"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "CALCULATE_BK"."LOAD_DATE" AS "LOAD_DATE"
		, "CALCULATE_BK"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "CALCULATE_BK"."JRN_FLAG" AS "JRN_FLAG"
		, "CALCULATE_BK"."RECORD_TYPE" AS "RECORD_TYPE"
		, "CALCULATE_BK"."P_PARTKEY" AS "P_PARTKEY"
		, "CALCULATE_BK"."P_PARTKEY_BK" AS "P_PARTKEY_BK"
		, "CALCULATE_BK"."P_NAME" AS "P_NAME"
		, "CALCULATE_BK"."P_MFGR" AS "P_MFGR"
		, "CALCULATE_BK"."P_BRAND" AS "P_BRAND"
		, "CALCULATE_BK"."P_TYPE" AS "P_TYPE"
		, "CALCULATE_BK"."P_SIZE" AS "P_SIZE"
		, "CALCULATE_BK"."P_CONTAINER" AS "P_CONTAINER"
		, "CALCULATE_BK"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "CALCULATE_BK"."P_COMMENT" AS "P_COMMENT"
		, "CALCULATE_BK"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
	FROM "CALCULATE_BK" "CALCULATE_BK"
	;
`} ).execute();

return "Done.";$$;
 
 
