CREATE OR REPLACE PROCEDURE "SF_SAMPLE_PROC"."SAT_TPCH_SUPPLIER_INCR"()
 RETURNS varchar 
LANGUAGE JAVASCRIPT 

AS $$ 
/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.1, generation date: 2023/06/17 03:45:02
DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 03:44:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/17 01:44:13, 
SRC_NAME: TPCH_SF1 - Release: TPCH_SF1(1) - Comment: Release 1 of TPCH - Release date: 2023/06/17 03:37:07
 */



var truncate_SAT_TEMP_TGT = snowflake.createStatement( {sqlText: `
	TRUNCATE TABLE "TPCH_SF1_STG"."SAT_TPCH_SUPPLIER_TMP";
`} ).execute();


var SAT_TEMP_TGT = snowflake.createStatement( {sqlText: `
	INSERT INTO "TPCH_SF1_STG"."SAT_TPCH_SUPPLIER_TMP"(
		 "SUPPLIER_HKEY"
		,"LOAD_DATE"
		,"LOAD_CYCLE_ID"
		,"RECORD_TYPE"
		,"SOURCE"
		,"EQUAL"
		,"HASH_DIFF"
		,"DELETE_FLAG"
		,"CDC_TIMESTAMP"
		,"S_SUPPKEY"
		,"S_COMMENT"
		,"S_NAME"
		,"S_NATIONKEY"
		,"LOAD_TIMESTAMP"
		,"S_PHONE"
		,"S_ADDRESS"
		,"S_ACCTBAL"
	)
	WITH "DIST_STG" AS 
	( 
		SELECT DISTINCT 
 			  "STG_DIS_SRC"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		FROM "TPCH_SF1_STG"."SUPPLIER" "STG_DIS_SRC"
		WHERE  "STG_DIS_SRC"."RECORD_TYPE" = 'S'
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP(NULL, 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."S_NAME"),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."S_ADDRESS")
				,'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."S_NATIONKEY")),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."S_PHONE"),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."S_ACCTBAL")),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."S_COMMENT"),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."LOAD_TIMESTAMP", 'DD/MM/YYYY HH24:MI:SS')),'~'),'\\#','\\\\' || '\\#')|| '\\#','\\#' || '~'),'~') )) AS "HASH_DIFF"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_TEMP_SRC"."S_SUPPKEY" AS "S_SUPPKEY"
			, "STG_TEMP_SRC"."S_COMMENT" AS "S_COMMENT"
			, "STG_TEMP_SRC"."S_NAME" AS "S_NAME"
			, "STG_TEMP_SRC"."S_NATIONKEY" AS "S_NATIONKEY"
			, "STG_TEMP_SRC"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
			, "STG_TEMP_SRC"."S_PHONE" AS "S_PHONE"
			, "STG_TEMP_SRC"."S_ADDRESS" AS "S_ADDRESS"
			, "STG_TEMP_SRC"."S_ACCTBAL" AS "S_ACCTBAL"
		FROM "TPCH_SF1_STG"."SUPPLIER" "STG_TEMP_SRC"
		WHERE  "STG_TEMP_SRC"."RECORD_TYPE" = 'S'
		UNION ALL 
		SELECT 
			  "SAT_SRC"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
			, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MAX("SAT_SRC"."LOAD_DATE")OVER( PARTITION BY "SAT_SRC"."SUPPLIER_HKEY") AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'SAT' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "SAT_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, "SAT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "SAT_SRC"."S_SUPPKEY" AS "S_SUPPKEY"
			, "SAT_SRC"."S_COMMENT" AS "S_COMMENT"
			, "SAT_SRC"."S_NAME" AS "S_NAME"
			, "SAT_SRC"."S_NATIONKEY" AS "S_NATIONKEY"
			, "SAT_SRC"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
			, "SAT_SRC"."S_PHONE" AS "S_PHONE"
			, "SAT_SRC"."S_ADDRESS" AS "S_ADDRESS"
			, "SAT_SRC"."S_ACCTBAL" AS "S_ACCTBAL"
		FROM "TPCH_DV_FL"."SAT_TPCH_SUPPLIER" "SAT_SRC"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "SAT_SRC"."SUPPLIER_HKEY" = "DIST_STG"."SUPPLIER_HKEY"
	)
	SELECT 
		  "TEMP_TABLE_SET"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND "TEMP_TABLE_SET"."DELETE_FLAG"::varchar || "TEMP_TABLE_SET"."HASH_DIFF"::varchar =
			LAG( "TEMP_TABLE_SET"."DELETE_FLAG"::varchar || "TEMP_TABLE_SET"."HASH_DIFF"::varchar,1)OVER(PARTITION BY "TEMP_TABLE_SET"."SUPPLIER_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "TEMP_TABLE_SET"."S_SUPPKEY" AS "S_SUPPKEY"
		, "TEMP_TABLE_SET"."S_COMMENT" AS "S_COMMENT"
		, "TEMP_TABLE_SET"."S_NAME" AS "S_NAME"
		, "TEMP_TABLE_SET"."S_NATIONKEY" AS "S_NATIONKEY"
		, "TEMP_TABLE_SET"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		, "TEMP_TABLE_SET"."S_PHONE" AS "S_PHONE"
		, "TEMP_TABLE_SET"."S_ADDRESS" AS "S_ADDRESS"
		, "TEMP_TABLE_SET"."S_ACCTBAL" AS "S_ACCTBAL"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"
	WHERE  "TEMP_TABLE_SET"."SOURCE" = 'STG' OR("TEMP_TABLE_SET"."LOAD_DATE" = "TEMP_TABLE_SET"."LOAD_END_DATE" AND "TEMP_TABLE_SET"."SOURCE" = 'SAT')
	;
`} ).execute();

var SAT_INUR_TGT = snowflake.createStatement( {sqlText: `
	INSERT INTO "TPCH_DV_FL"."SAT_TPCH_SUPPLIER"(
		 "SUPPLIER_HKEY"
		,"LOAD_DATE"
		,"LOAD_CYCLE_ID"
		,"HASH_DIFF"
		,"DELETE_FLAG"
		,"CDC_TIMESTAMP"
		,"S_SUPPKEY"
		,"S_COMMENT"
		,"S_NAME"
		,"S_NATIONKEY"
		,"LOAD_TIMESTAMP"
		,"S_PHONE"
		,"S_ADDRESS"
		,"S_ACCTBAL"
	)
	SELECT 
		  "SAT_TEMP_SRC_INUR"."SUPPLIER_HKEY" AS "SUPPLIER_HKEY"
		, "SAT_TEMP_SRC_INUR"."LOAD_DATE" AS "LOAD_DATE"
		, "SAT_TEMP_SRC_INUR"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "SAT_TEMP_SRC_INUR"."HASH_DIFF" AS "HASH_DIFF"
		, "SAT_TEMP_SRC_INUR"."DELETE_FLAG" AS "DELETE_FLAG"
		, "SAT_TEMP_SRC_INUR"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "SAT_TEMP_SRC_INUR"."S_SUPPKEY" AS "S_SUPPKEY"
		, "SAT_TEMP_SRC_INUR"."S_COMMENT" AS "S_COMMENT"
		, "SAT_TEMP_SRC_INUR"."S_NAME" AS "S_NAME"
		, "SAT_TEMP_SRC_INUR"."S_NATIONKEY" AS "S_NATIONKEY"
		, "SAT_TEMP_SRC_INUR"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		, "SAT_TEMP_SRC_INUR"."S_PHONE" AS "S_PHONE"
		, "SAT_TEMP_SRC_INUR"."S_ADDRESS" AS "S_ADDRESS"
		, "SAT_TEMP_SRC_INUR"."S_ACCTBAL" AS "S_ACCTBAL"
	FROM "TPCH_SF1_STG"."SAT_TPCH_SUPPLIER_TMP" "SAT_TEMP_SRC_INUR"
	WHERE  "SAT_TEMP_SRC_INUR"."SOURCE" = 'STG' AND "SAT_TEMP_SRC_INUR"."EQUAL" = 0
	;
`} ).execute();

return "Done.";$$;
 
 
