CREATE OR REPLACE PROCEDURE "SF_SAMPLE_PROC"."SAT_TPCH_PART_INCR"()
 RETURNS varchar 
LANGUAGE JAVASCRIPT 

AS $$ 
/*
 __     __          _ _                           _      __  ___  __   __   
 \ \   / /_ _ _   _| | |_ ___ ____   ___  ___  __| |     \ \/ _ \/ /  /_/   
  \ \ / / _` | | | | | __/ __|  _ \ / _ \/ _ \/ _` |      \/ / \ \/ /\      
   \ V / (_| | |_| | | |_\__ \ |_) |  __/  __/ (_| |      / / \/\ \/ /      
    \_/ \__,_|\__,_|_|\__|___/ .__/ \___|\___|\__,_|     /_/ \/_/\__/       
                             |_|                                            

Vaultspeed version: 5.3.1.1, generation date: 2023/06/17 03:45:02
DV_NAME: TPCH_DV - Release: TPCH_DV_1(1) - Comment: Release 1 of TPCH_DV - Release date: 2023/06/17 03:44:00, 
BV release: init(1) - Comment: initial release - Release date: 2023/06/17 01:44:13, 
SRC_NAME: TPCH_SF1 - Release: TPCH_SF1(1) - Comment: Release 1 of TPCH - Release date: 2023/06/17 03:37:07
 */



var truncate_SAT_TEMP_TGT = snowflake.createStatement( {sqlText: `
	TRUNCATE TABLE "TPCH_SF1_STG"."SAT_TPCH_PART_TMP";
`} ).execute();


var SAT_TEMP_TGT = snowflake.createStatement( {sqlText: `
	INSERT INTO "TPCH_SF1_STG"."SAT_TPCH_PART_TMP"(
		 "PART_HKEY"
		,"LOAD_DATE"
		,"LOAD_CYCLE_ID"
		,"RECORD_TYPE"
		,"SOURCE"
		,"EQUAL"
		,"HASH_DIFF"
		,"DELETE_FLAG"
		,"CDC_TIMESTAMP"
		,"P_PARTKEY"
		,"P_CONTAINER"
		,"P_MFGR"
		,"P_TYPE"
		,"P_SIZE"
		,"P_RETAILPRICE"
		,"P_COMMENT"
		,"P_NAME"
		,"LOAD_TIMESTAMP"
		,"P_BRAND"
	)
	WITH "DIST_STG" AS 
	( 
		SELECT DISTINCT 
 			  "STG_DIS_SRC"."PART_HKEY" AS "PART_HKEY"
			, "STG_DIS_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		FROM "TPCH_SF1_STG"."PART" "STG_DIS_SRC"
		WHERE  "STG_DIS_SRC"."RECORD_TYPE" = 'S'
	)
	, "TEMP_TABLE_SET" AS 
	( 
		SELECT 
			  "STG_TEMP_SRC"."PART_HKEY" AS "PART_HKEY"
			, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, TO_TIMESTAMP(NULL, 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
			, "STG_TEMP_SRC"."RECORD_TYPE" AS "RECORD_TYPE"
			, 'STG' AS "SOURCE"
			, 1 AS "ORIGIN_ID"
			, UPPER(MD5_HEX(COALESCE(RTRIM( REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_NAME"),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_MFGR")
				,'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_BRAND"),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_TYPE"),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."P_SIZE")),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_CONTAINER"),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."P_RETAILPRICE")),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( "STG_TEMP_SRC"."P_COMMENT"),'~'),'\\#','\\\\' || '\\#')|| '\\#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."LOAD_TIMESTAMP", 'DD/MM/YYYY HH24:MI:SS')),'~'),'\\#','\\\\' || '\\#')|| '\\#','\\#' || '~'),'~') )) AS "HASH_DIFF"
			, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y' AS VARCHAR) ELSE CAST('N' AS VARCHAR) END AS "DELETE_FLAG"
			, "STG_TEMP_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "STG_TEMP_SRC"."P_PARTKEY" AS "P_PARTKEY"
			, "STG_TEMP_SRC"."P_CONTAINER" AS "P_CONTAINER"
			, "STG_TEMP_SRC"."P_MFGR" AS "P_MFGR"
			, "STG_TEMP_SRC"."P_TYPE" AS "P_TYPE"
			, "STG_TEMP_SRC"."P_SIZE" AS "P_SIZE"
			, "STG_TEMP_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "STG_TEMP_SRC"."P_COMMENT" AS "P_COMMENT"
			, "STG_TEMP_SRC"."P_NAME" AS "P_NAME"
			, "STG_TEMP_SRC"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
			, "STG_TEMP_SRC"."P_BRAND" AS "P_BRAND"
		FROM "TPCH_SF1_STG"."PART" "STG_TEMP_SRC"
		WHERE  "STG_TEMP_SRC"."RECORD_TYPE" = 'S'
		UNION ALL 
		SELECT 
			  "SAT_SRC"."PART_HKEY" AS "PART_HKEY"
			, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
			, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
			, MAX("SAT_SRC"."LOAD_DATE")OVER( PARTITION BY "SAT_SRC"."PART_HKEY") AS "LOAD_END_DATE"
			, 'SAT' AS "RECORD_TYPE"
			, 'SAT' AS "SOURCE"
			, 0 AS "ORIGIN_ID"
			, "SAT_SRC"."HASH_DIFF" AS "HASH_DIFF"
			, "SAT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
			, "SAT_SRC"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
			, "SAT_SRC"."P_PARTKEY" AS "P_PARTKEY"
			, "SAT_SRC"."P_CONTAINER" AS "P_CONTAINER"
			, "SAT_SRC"."P_MFGR" AS "P_MFGR"
			, "SAT_SRC"."P_TYPE" AS "P_TYPE"
			, "SAT_SRC"."P_SIZE" AS "P_SIZE"
			, "SAT_SRC"."P_RETAILPRICE" AS "P_RETAILPRICE"
			, "SAT_SRC"."P_COMMENT" AS "P_COMMENT"
			, "SAT_SRC"."P_NAME" AS "P_NAME"
			, "SAT_SRC"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
			, "SAT_SRC"."P_BRAND" AS "P_BRAND"
		FROM "TPCH_DV_FL"."SAT_TPCH_PART" "SAT_SRC"
		INNER JOIN "DIST_STG" "DIST_STG" ON  "SAT_SRC"."PART_HKEY" = "DIST_STG"."PART_HKEY"
	)
	SELECT 
		  "TEMP_TABLE_SET"."PART_HKEY" AS "PART_HKEY"
		, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
		, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "TEMP_TABLE_SET"."RECORD_TYPE" AS "RECORD_TYPE"
		, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
		, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND "TEMP_TABLE_SET"."DELETE_FLAG"::varchar || "TEMP_TABLE_SET"."HASH_DIFF"::varchar =
			LAG( "TEMP_TABLE_SET"."DELETE_FLAG"::varchar || "TEMP_TABLE_SET"."HASH_DIFF"::varchar,1)OVER(PARTITION BY "TEMP_TABLE_SET"."PART_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE","TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
		, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
		, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
		, "TEMP_TABLE_SET"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "TEMP_TABLE_SET"."P_PARTKEY" AS "P_PARTKEY"
		, "TEMP_TABLE_SET"."P_CONTAINER" AS "P_CONTAINER"
		, "TEMP_TABLE_SET"."P_MFGR" AS "P_MFGR"
		, "TEMP_TABLE_SET"."P_TYPE" AS "P_TYPE"
		, "TEMP_TABLE_SET"."P_SIZE" AS "P_SIZE"
		, "TEMP_TABLE_SET"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "TEMP_TABLE_SET"."P_COMMENT" AS "P_COMMENT"
		, "TEMP_TABLE_SET"."P_NAME" AS "P_NAME"
		, "TEMP_TABLE_SET"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		, "TEMP_TABLE_SET"."P_BRAND" AS "P_BRAND"
	FROM "TEMP_TABLE_SET" "TEMP_TABLE_SET"
	WHERE  "TEMP_TABLE_SET"."SOURCE" = 'STG' OR("TEMP_TABLE_SET"."LOAD_DATE" = "TEMP_TABLE_SET"."LOAD_END_DATE" AND "TEMP_TABLE_SET"."SOURCE" = 'SAT')
	;
`} ).execute();

var SAT_INUR_TGT = snowflake.createStatement( {sqlText: `
	INSERT INTO "TPCH_DV_FL"."SAT_TPCH_PART"(
		 "PART_HKEY"
		,"LOAD_DATE"
		,"LOAD_CYCLE_ID"
		,"HASH_DIFF"
		,"DELETE_FLAG"
		,"CDC_TIMESTAMP"
		,"P_PARTKEY"
		,"P_CONTAINER"
		,"P_MFGR"
		,"P_TYPE"
		,"P_SIZE"
		,"P_RETAILPRICE"
		,"P_COMMENT"
		,"P_NAME"
		,"LOAD_TIMESTAMP"
		,"P_BRAND"
	)
	SELECT 
		  "SAT_TEMP_SRC_INUR"."PART_HKEY" AS "PART_HKEY"
		, "SAT_TEMP_SRC_INUR"."LOAD_DATE" AS "LOAD_DATE"
		, "SAT_TEMP_SRC_INUR"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, "SAT_TEMP_SRC_INUR"."HASH_DIFF" AS "HASH_DIFF"
		, "SAT_TEMP_SRC_INUR"."DELETE_FLAG" AS "DELETE_FLAG"
		, "SAT_TEMP_SRC_INUR"."CDC_TIMESTAMP" AS "CDC_TIMESTAMP"
		, "SAT_TEMP_SRC_INUR"."P_PARTKEY" AS "P_PARTKEY"
		, "SAT_TEMP_SRC_INUR"."P_CONTAINER" AS "P_CONTAINER"
		, "SAT_TEMP_SRC_INUR"."P_MFGR" AS "P_MFGR"
		, "SAT_TEMP_SRC_INUR"."P_TYPE" AS "P_TYPE"
		, "SAT_TEMP_SRC_INUR"."P_SIZE" AS "P_SIZE"
		, "SAT_TEMP_SRC_INUR"."P_RETAILPRICE" AS "P_RETAILPRICE"
		, "SAT_TEMP_SRC_INUR"."P_COMMENT" AS "P_COMMENT"
		, "SAT_TEMP_SRC_INUR"."P_NAME" AS "P_NAME"
		, "SAT_TEMP_SRC_INUR"."LOAD_TIMESTAMP" AS "LOAD_TIMESTAMP"
		, "SAT_TEMP_SRC_INUR"."P_BRAND" AS "P_BRAND"
	FROM "TPCH_SF1_STG"."SAT_TPCH_PART_TMP" "SAT_TEMP_SRC_INUR"
	WHERE  "SAT_TEMP_SRC_INUR"."SOURCE" = 'STG' AND "SAT_TEMP_SRC_INUR"."EQUAL" = 0
	;
`} ).execute();

return "Done.";$$;
 
 
